ALTER TABLE users 
ADD COLUMN profile_picture VARCHAR(255) DEFAULT NULL,
ADD COLUMN department VARCHAR(100) DEFAULT NULL,
ADD COLUMN year_level VARCHAR(20) DEFAULT NULL,
ADD COLUMN bio TEXT DEFAULT NULL,
ADD COLUMN last_active DATETIME DEFAULT NULL; 